apiVersion: v1
kind: ConfigMap
metadata:
  name: commune-drop-frontend-configmap
  labels:
    app: commune-drop-frontend-configmap
data:
  VITE_LOCATION_CLIENT_ID: "microservice_location_client"
  VITE_ORDER_CLIENT_ID: "microservice_order_client"
  VITE_SUPABASE_URL: "https://pdymjbbdxlmavkkxxori.supabase.co/"
  VITE_WEBSOCKET_URL: "http://commune-drop-service:3001/"
  VITE_PAYMENT_SERVICE_URL: "http://payment-service:80"
  VITE_ORDER_SERVICE_URL: "http://order-service:80/order"
  VITE_LOCATION_SERVICE_URL: "http://location-service:80/location"
  VITE_API_BASE_URL: "http://auth-service:80"

  # VITE_WEBSOCKET_URL: "http://commune-drop-service:81/"
#